language: node_js
sudo: false
node_js:
  - "15"
  - "14"
  - "12"
matrix:
  allow_failures:
    - node_js: "15"

before_install:
  # Upgrade npm to avoid semver issues
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
